all:
  - name: mine adobe
    miner: AdobeCreativeMiner
    outputs:
      - resultPath: ./docs/AdobeCreativeMiner.json
        filter: '[]'
  - name: mine azure
    miner: AzureWithServiceTagsMiner
    outputs:
      - resultPath: ./docs/AzureWithServiceTagsMiner.json
        filter: "[?systemService=='AzureAD']"
  - name: mine o365
    miner: O365Miner
    outputs:
      - resultPath: ./docs/O365Miner.json
        filter: "[?serviceArea=='Common']"
