all:
  - name: mine adobe
    miner: AdobeCreativeMiner
    outputs:
      - resultPath: ./docs/AdobeCreativeMiner.json
        filter: '[]'
  - name: mine azure
    miner: AzureWithServiceTagsMiner
    outputs:
      - resultPath: ./docs/AzureWithServiceTagsMiner.json
        filter: "[?systemService=='AzureAD']"
  - name: mine o365
    miner: O365Miner
    outputs:
      - resultPath: ./docs/O365Miner.json
        filter: "[?serviceArea=='Common']"
  - name: mine google cloud netblocks
    miner: GoogleCloudNetblocksMiner
    outputs:
      - resultPath: ./docs/GoogleCloudNetblocksMiner.json
        filter: "[?scope=='europe-west6']"
  - name: mine google netblocks
    miner: GoogleNetblocksMiner
    outputs:
      - resultPath: ./docs/GoogleNetblocksMiner.json
  - name: mine AWS ip ranges
    miner: AWSIPRangesMiner
    outputs:
      - resultPath: ./docs/AWSIPRangesMiner.json
        filter: "[?region=='eu-south-1']"
  - name: mine FB registered routes
    miner: RADBASRegisterdRoutesMiner
    args:
      autonomous_system: AS32934
    outputs:
      - resultPath: ./docs/RADBASRegisterdRoutesMiner.json
        filter: "[]"
  - name: mine FB announced prefixes
    miner: BGPViewASNPrefixMiner
    args:
      autonomous_system: AS32934
    outputs:
      - resultPath: ./docs/BGPViewASNPrefixMiner.json
        filter: "[]"
