name: 'integration-tests'
on:
  schedule:
    - cron: '14 3 * * *'
  workflow_dispatch:
    inputs:
      update_docs:
        description: "Update documentation?"
jobs:
  generate-miners-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: |-
          npm install
      - name: mine
        uses: ./
        with:
          config: ./docs/generate-miners-samples-config.yml
          configSection: all
        env:
          O365MINER_CLIENT_GUID: ${{ secrets.O365MINER_CLIENT_GUID }}
      - name: validate mined samples
        run: |-
          for d in ./docs/*.json; do
            ./node_modules/.bin/ajv test -d "${d}" -s "./docs/schemas/${${d%%.json}##./docs/}.schema.json" --valid
          done
      - name: Add & Commit & Push
        if: ${{ github.event.inputs.update_docs != '' }}
        run: |-
          git config user.name "Automated Generate Miners Samples"
          git config user.email "actions@users.noreply.github.com"
          git add docs
          timestamp=$(date -u)
          git commit -m "Updated samples: ${timestamp}" || exit 0
          git push
