name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create temp dir
        run: mkdir -p ./temp
      - name: mine
        uses: ./
        with:
          config: ./__tests__/test-config.yml
          configSection: test1
      - name: process
        uses: jtschichold/mm-process-url-list@2ae39d5
        with:
          list: './temp/*.lst'
          outFormat: PANOSURL
          result: './temp/cloud-services.lst'
